apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
spec:
  ingressClassName: nginx
  rules:
    - host: &host draw.cloudton.de
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: excalidraw
                port:
                  name: http
  tls:
    - secretName: excalidraw-tls-certificate
      hosts:
        - *host
