hajimari:
  env:
    TZ: Europe/Berlin
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "ipv4.cloudton.de"
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.cloudton.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    globalBookmarks:
      - group: Homelab
        bookmarks:
          - name: Documentation
            url: https://homelab.cloudton.de
          - name: Public GitHub repository
            url: https://github.com/khuedoan/homelab
      - group: Managed services
        bookmarks:
          - name: Terraform Cloud
            url: https://app.terraform.io
          - name: Cloudflare
            url: https://dash.cloudflare.com
  persistence:
    data:
      enabled: false
