k8up:
  k8up:
    envVars:
      - name: BACKUP_PROMURL
        value: "http://monitoring-system-prometheus-pushgateway.monitoring-system:9091/"
      - name: BACKUP_GLOBAL_OPERATOR_NAMESPACE
        value: "k8up"
      - name: BACKUP_GLOBAL_FAILED_JOBS_HISTORY_LIMIT
        value: "1"
      - name: BACKUP_GLOBAL_SUCCESSFUL_JOBS_HISTORY_LIMIT
        value: "1"
      - name: BACKUP_GLOBALS3ENDPOINT
        value: "https://s3.eu-central-003.backblazeb2.com"
      - name: BACKUP_GLOBALS3BUCKET
        value: "homelab-k8up"
      - name: BACKUP_GLOBALACCESSKEYID
        valueFrom:
          secretKeyRef:
            name: backblaze-k8up
            key: ACCESS_KEY_ID
      - name: BACKUP_GLOBALSECRETACCESSKEY
        valueFrom:
          secretKeyRef:
            name: backblaze-k8up
            key: ACCESS_SECRET_KEY
      - name: BACKUP_GLOBALREPOPASSWORD
        valueFrom:
          secretKeyRef:
            name: k8up-secrets
            key: repo-password
