apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-configs
data:
  litellm.yaml: |-
    general_settings:
      store_model_in_db: true
      store_prompts_in_spend_logs: true
    provider_budget_config:
      vercel_ai_gateway:
        budget_limit: 1.0
        time_period: "1d"
    router_settings:
      fallbacks: [ { "claude-sonnet-4-5": [ "copilot/claude-sonnet-4-5" ] }, { "claude-haiku-4-5": [ "copilot/claude-haiku-4-5" ] } ]
    model_list:
      # CLAUDE OPUS 4.5
      - model_name: copilot/claude-opus-4-5
        litellm_params:
          model: github_copilot/claude-opus-4.5
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }

      # CLAUDE SONNET 4.5
      - model_name: claude-sonnet-4-5
        litellm_params:
          model: openai/claude-sonnet-4-5-20250929
          api_base: http://ai-cliproxyapi:8317/v1
          api_key: sk-dummy
        model_info:
          input_cost_per_token: 3e-06
          output_cost_per_token: 1.5e-05
      - model_name: copilot/claude-sonnet-4-5
        litellm_params:
          model: github_copilot/claude-sonnet-4.5
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }
        model_info:
          input_cost_per_token: 3e-06
          output_cost_per_token: 1.5e-05
      - model_name: vercel_ai_gateway/claude-sonnet-4-5
        litellm_params:
          model: vercel_ai_gateway/anthropic/claude-sonnet-4.5
          api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY
        model_info:
          input_cost_per_token: 3e-06
          output_cost_per_token: 1.5e-05

      # CLAUDE HAIKU 4.5
      - model_name: claude-haiku-4-5
        litellm_params:
          model: openai/claude-haiku-4-5-20251001
          api_base: http://ai-cliproxyapi:8317/v1
          api_key: sk-dummy
        model_info:
          input_cost_per_token: 1e-06
          output_cost_per_token: 5e-06
      - model_name: copilot/claude-haiku-4-5
        litellm_params:
          model: github_copilot/claude-haiku-4.5
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }
        model_info:
          input_cost_per_token: 1e-06
          output_cost_per_token: 5e-06
      - model_name: vercel_ai_gateway/claude-haiku-4-5
        litellm_params:
          model: vercel_ai_gateway/anthropic/claude-haiku-4.5
          api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY
        model_info:
          input_cost_per_token: 1e-06
          output_cost_per_token: 5e-06

      # GPT 5.1 CODEX
      - model_name: gpt-5.1-codex
        model_info:
          mode: responses
        litellm_params:
          model: github_copilot/gpt-5.1-codex
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }
      - model_name: vercel_ai_gateway/gpt-5.1-codex
        litellm_params:
          model: vercel_ai_gateway/openai/gpt-5.1-codex
          api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY

      # GEMINI
      - model_name: gemini-3-pro-preview
        litellm_params:
          model: gemini/gemini-3-pro-preview
          api_base: http://ai-gemini:8888
          api_key: sk-dummy
      - model_name: gemini-2.5-pro
        litellm_params:
          model: gemini/gemini-2.5-pro
          api_base: http://ai-gemini:8888
          api_key: sk-dummy
      - model_name: gemini-2.5-flash
        litellm_params:
          model: gemini/gemini-2.5-flash
          api_base: http://ai-gemini:8888
          api_key: sk-dummy

      # FREE COPILOT
      - model_name: gpt-5-mini
        litellm_params:
          model: github_copilot/gpt-5-mini
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }
      - model_name: gpt-4o
        litellm_params:
          model: github_copilot/gpt-4o
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }
      - model_name: gpt-4.1
        litellm_params:
          model: github_copilot/gpt-4.1
          extra_headers: { "editor-version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat" }

      # GLM
      - model_name: glm-4.6
        litellm_params:
          model: openai/glm-4.6
          api_base: https://api.z.ai/api/coding/paas/v4
          api_key: os.environ/ZAI_API_KEY
        model_info:
          input_cost_per_token: 4.5e-07
          output_cost_per_token: 1.8e-06

      # QWEN3
      - model_name: qwen3-coder
        litellm_params:
          model: Qwen/Qwen3-Coder-480B-A35B-Instruct
          api_base: https://api.tokenfactory.nebius.com/v1
          api_key: os.environ/NEBIUS_API_KEY
        model_info:
          input_cost_per_token: 4.0e-07
          output_cost_per_token: 1.8e-06

  cliproxyapi.yaml: |-
    port: 8317
    auth-dir: "/root/.cli-proxy-api"
